[package]
name = "websocat"
version = "3.0.0"
authors = ["Vitaly _Vi Shukela <vi0oss@gmail.com>"]
edition = "2018"

[dependencies]
websocat-api = {path="websocat-api"}


[workspace]
members = [
    "websocat-api",
    "websocat-derive",
    "websocat-basic",
    "playground",
]